### ISSUE TITLE
re-write all the test nodes using the new base controller

### ISSUE THREAD

**Issue by princeward** [StanfordMSL/msl_quad#1]
Currently, ```actuator_test```, ```pos_ctrl_test```, ```vel_ctrl_test``` are still using the old code. We need to rewrite them using the new ```PX4BaseController``` class. Ideally, all test nodes should be inside a single ```test``` folder.

This should be pretty straightforward and good practice for contributing to the codebase. Let me know if you are interested or have any questions.

**Comment by exoticDFT** [comment]
Moved to Jira: https://asjira.stanford.edu/jira/projects/MSLQ/summary
