### ISSUE TITLE
monitor vision_pose and local_position in slowLoop for safety

### ISSUE THREAD

**Issue by princeward** [StanfordMSL/msl_quad#2]
As a safety feature, in the slowLoop(), check:

1. Check whether the quad is constantly receiving mocap/local_position. If no new message after 0.5s, throw warning. If no new message after 1.0s, throw error message.

2. Check if mocap/local_position estimates are close enough. If difference exceeds threshold, throw warning/error message

**Comment by exoticDFT** [comment]
Moved to Jira: https://asjira.stanford.edu/jira/projects/MSLQ/summary
