### ISSUE TITLE
Software Documentation - Quick Start Guide

### ISSUE THREAD

**Issue by exoticDFT** [StanfordMSL/msl_quad#20]
We need to add a "Quick Start Guide/Checklist" section under the "Hardware" section of our documentation. See this link for full layout https://stanford-msl.slack.com/archives/CBLRMNEQ7/p1566425187004900

This will have subsections for each of the following:

- [ ] Quad setup
- [ ] Namespace guide
- [ ] Launch files

**Comment by harukins** [comment]
Moved to Jira: https://asjira.stanford.edu/jira/projects/MSLQ/summary
