### ISSUE TITLE
Add initial code for ReadTheDocs documentation to the repo

### ISSUE THREAD

**Issue by exoticDFT** [StanfordMSL/msl_quad#25]
We need to run the initial configuration for setting up ReadTheDocs for a repository. This can be done by following the information found [here](https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html).

**Comment by exoticDFT** [comment]
I believe this was done during the last meeting. However, I am adding this for tracking purposes and to verify we have completed the task.

**Comment by k2shah** [comment]
@exoticDFT  is this done? I'll start the PR for the doc branch to be merged #44

**Comment by k2shah** [comment]
closed by #44
